### ISSUE TITLE
Labled basic button issue in docs

### ISSUE THREAD

**Issue by princeandrew01** [hammy2899/Fomantic-UI#38]
![image](https://user-images.githubusercontent.com/13138963/41923814-708e310e-7936-11e8-87ba-e8def8a8546d.png)

Good Day, 

I noticed something strange in the docs when I was looking under buttons. The above image shows the labelled basic button is completely coloured except when hovering over it. I have not seen it personally in any of my buttons but can it be fixed in the docs?

P.S. I am really glad someone took up the torch of continuing the development. The two upcoming ui elements being integrated where ones I have been waiting for awhile.

**Comment by hammy2899** [comment]
Looking at [semantic-ui.com](https://semantic-ui.com) instead of [fomantic-ui.com](https://fomantic-ui.com)?
